---
title: "Islands of Fertility"
output: html_document
---

```{r, echo=FALSE}
library(tidyverse)
library(lme4)
library(lmerTest)
library(emmeans)

```

```{r, echo=FALSE}
soil <- read.csv("2020062020_research_allsamples_.csv")
soil$ring <- as.factor(soil$ring)
soil$depth <- as.factor(soil$depth)


amdu <- filter(soil, plant == "INSP" | plant == "AMDU")
latr <- filter(soil, plant == "INSP" | plant == "LATR")
lyan <- filter(soil, plant == "INSP" | plant == "LYAN")
lypa <- filter(soil, plant == "INSP" | plant == "LYPA")
plri <- filter(soil, plant == "INSP" | plant == "PLRI")
```
# AMDU Graph
```{r plot of %C}
means <-amdu %>% 
  group_by(plant, treatment, depth) %>%
  summarize(N=length(mgCgsoil),
            mean_C=mean(mgCgsoil,na.rm=TRUE),
            sd_C=sd(mgCgsoil,na.rm=TRUE),
            se_C=sd_C/sqrt(N))


bp.C <- ggplot(means, aes(x=mean_C, y=depth,color=treatment,group=treatment))+
  geom_point(size=3, pch=18)+
  facet_grid(.~plant)+
  geom_errorbar(aes(xmin=mean_C-sd_C, xmax=mean_C+sd_C), width=.1)+
  geom_path(col="grey")+
  scale_y_discrete(limits=rev(levels(means$depth)))+
  scale_color_manual(values = c("#808080","#000000"))+
  theme_bw() +
  theme(panel.border = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   labs(x="mg C/ g soil", y="Depth (cm)")
bp.C
```


```{r amdu, echo=FALSE}
# The statistical model 
# Change data= to correct plant type
lmer.amdu <- lmer(mgCgsoil~(treatment+plant+depth)^3+(1|ring), data=amdu)

# Checking for normality assumptions
plot(predict(lmer.amdu), residuals(lmer.amdu)) 
qqnorm(residuals(lmer.amdu)); qqline(residuals(lmer.amdu))
hist(residuals(lmer.amdu)) 

sum.1 <- summary(lmer.amdu)
sum.1
a1 <- anova(lmer.amdu) 
a1
summary(a1)

#p values
estimates.amdu <- summary(emmeans(lmer.amdu, ~ treatment+plant+depth),  type="response")
estimates.amdu

paircomp.amdu <- summary(emmeans(lmer.amdu, pairwise~plant|treatment|depth)$contrasts)
paircomp.amdu

paircomp.amdu.trt <- summary(emmeans(lmer.amdu, pairwise~ treatment|plant|depth)$contrasts)
View(paircomp.amdu.trt)


# At what depth(s) is there an island of fertility effect? 20 cm
# Does the island of fertility effect change with CO2 treatment? yes
# If yes, what caused the change? A change in INSP or a change in AMDU carbon? change in AMDU 
```


# LATR Graph
```{r plot of %C}
means <-latr %>% 
  group_by(plant, treatment, depth) %>%
  summarize(N=length(mgCgsoil),
            mean_C=mean(mgCgsoil,na.rm=TRUE),
            sd_C=sd(mgCgsoil,na.rm=TRUE),
            se_C=sd_C/sqrt(N))


bp.C <- ggplot(means, aes(x=mean_C, y=depth,color=treatment,group=treatment))+
  geom_point(size=3, pch=18)+
  facet_grid(.~plant)+
  geom_errorbar(aes(xmin=mean_C-sd_C, xmax=mean_C+sd_C), width=.1)+
  geom_path(col="grey")+
  scale_y_discrete(limits=rev(levels(means$depth)))+
  scale_color_manual(values = c("#808080","#000000"))+
  theme_bw() +
  theme(panel.border = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   labs(x="mg C/ g soil", y="Depth (cm)")
bp.C
```

```{r LATR, echo=FALSE}
# The statistical model 
# Change data= to correct plant type
lmer.latr <- lmer(log(mgCgsoil)~(treatment+plant+depth)^3+(1|ring), data=latr)

# Checking for normality assumptions
plot(predict(lmer.latr), residuals(lmer.latr)) 
qqnorm(residuals(lmer.latr)); qqline(residuals(lmer.latr))
hist(residuals(lmer.latr)) 

sum.2 <- summary(lmer.latr)
sum.2
a2 <- anova(lmer.latr) 
a2


#p values
estimates.latr <- summary(emmeans(lmer.latr, ~ treatment+plant+depth),  type="response")
estimates.latr

paircomp.latr <- summary(emmeans(lmer.latr, pairwise~plant|treatment|depth)$contrasts)
paircomp.latr

paircomp.latr.trt <- summary(emmeans(lmer.latr, pairwise~ treatment|plant|depth)$contrasts)
View(paircomp.latr.trt)
```

# LYAN Graph
```{r plot of %C}
means <-lyan %>% 
  group_by(plant, treatment, depth) %>%
  summarize(N=length(mgCgsoil),
            mean_C=mean(mgCgsoil,na.rm=TRUE),
            sd_C=sd(mgCgsoil,na.rm=TRUE),
            se_C=sd_C/sqrt(N))


bp.C <- ggplot(means, aes(x=mean_C, y=depth,color=treatment,group=treatment))+
  geom_point(size=3, pch=18)+
  facet_grid(.~plant)+
  geom_errorbar(aes(xmin=mean_C-sd_C, xmax=mean_C+sd_C), width=.1)+
  geom_path(col="grey")+
  scale_y_discrete(limits=rev(levels(means$depth)))+
  scale_color_manual(values = c("#808080","#000000"))+
  theme_bw() +
  theme(panel.border = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   labs(x="mg C/ g soil", y="Depth (cm)")
bp.C
```
#LYAN Statistical Ananlysis of CO2 effect
```{r LYAN, echo=FALSE}
# The statistical model 
# Change data= to correct plant type
lmer.lyan <- lmer(mgCgsoil~(treatment+plant+depth)^3+(1|ring), data=lyan)

# Checking for normality assumptions
plot(predict(lmer.lyan), residuals(lmer.lyan)) 
qqnorm(residuals(lmer.lyan)); qqline(residuals(lmer.lyan))
hist(residuals(lmer.lyan)) 


sum.2 <- summary(lmer.lyan)
sum.2
a2 <- anova(lmer.lyan) 
a2


# p values
estimates.lyan <- summary(emmeans(lmer.lyan, ~ treatment+plant+depth),  type="response")
estimates.lyan

paircomp.lyan <- summary(emmeans(lmer.lyan, pairwise~plant|treatment|depth)$contrasts)
paircomp.lyan

paircomp.lyan.trt <- summary(emmeans(lmer.lyan, pairwise~ treatment|plant|depth)$contrasts)
View(paircomp.lyan.trt)
```

# LYPA Graph
```{r plot of %C}
means <-lypa %>% 
  group_by(plant, treatment, depth) %>%
  summarize(N=length(mgCgsoil),
            mean_C=mean(mgCgsoil,na.rm=TRUE),
            sd_C=sd(mgCgsoil,na.rm=TRUE),
            se_C=sd_C/sqrt(N))


bp.C <- ggplot(means, aes(x=mean_C, y=depth,color=treatment,group=treatment))+
  geom_point(size=3, pch=18)+
  facet_grid(.~plant)+
  geom_errorbar(aes(xmin=mean_C-sd_C, xmax=mean_C+sd_C), width=.1)+
  geom_path(col="grey")+
  scale_y_discrete(limits=rev(levels(means$depth)))+
  scale_color_manual(values = c("#808080","#000000"))+
  theme_bw() +
  theme(panel.border = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   labs(x="mg C/ g soil", y="Depth (cm)")
bp.C
```
```{r LYPA, echo=FALSE}
# The statistical model 
# Change data= to correct plant type
lmer.lypa <- lmer(log(mgCgsoil)~(treatment+plant+depth)^3+(1|ring), data=lypa)

# Checking for normality assumptions
plot(predict(lmer.lypa), residuals(lmer.lypa)) 
qqnorm(residuals(lmer.lypa)); qqline(residuals(lmer.lypa))
hist(residuals(lmer.lypa)) 


sum.2 <- summary(lmer.lypa)
sum.2
a2 <- anova(lmer.lypa) 
a2


#p values 
estimates.lypa <- summary(emmeans(lmer.lypa, ~ treatment+plant+depth),  type="response")
estimates.lypa

paircomp.lypa <- summary(emmeans(lmer.lypa, pairwise~plant|treatment|depth)$contrasts)
paircomp.lypa

paircomp.lypa.trt <- summary(emmeans(lmer.lypa, pairwise~ treatment|plant|depth)$contrasts)
View(paircomp.lypa.trt)
```

# PLRI Graph
```{r plot of %C}
means <-plri %>% 
  group_by(plant, treatment, depth) %>%
  summarize(N=length(mgCgsoil),
            mean_C=mean(mgCgsoil,na.rm=TRUE),
            sd_C=sd(mgCgsoil,na.rm=TRUE),
            se_C=sd_C/sqrt(N))


bp.C <- ggplot(means, aes(x=mean_C, y=depth,color=treatment,group=treatment))+
  geom_point(size=3, pch=18)+
  facet_grid(.~plant)+
  geom_errorbar(aes(xmin=mean_C-sd_C, xmax=mean_C+sd_C), width=.1)+
  geom_path(col="grey")+
  scale_y_discrete(limits=rev(levels(means$depth)))+
  scale_color_manual(values = c("#808080","#000000"))+
  theme_bw() +
  theme(panel.border = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"))+
   labs(x="mg C/ g soil", y="Depth (cm)")
bp.C
```

```{r PLRI, echo=FALSE}
# The statistical model 
# Change data= to correct plant type
lmer.plri <- lmer(mgCgsoil~(treatment+plant+depth)^3+(1|ring), data=plri)

# Checking for normality assumptions
plot(predict(lmer.plri), residuals(lmer.plri)) 
qqnorm(residuals(lmer.plri)); qqline(residuals(lmer.plri))
hist(residuals(lmer.plri)) 


sum.2 <- summary(lmer.plri)
sum.2
a2 <- anova(lmer.plri) 
a2


# p values 
estimates.plri <- summary(emmeans(lmer.plri, ~ treatment+plant+depth),  type="response")
estimates.plri

paircomp.plri <- summary(emmeans(lmer.plri, pairwise~plant|treatment|depth)$contrasts)
paircomp.plri

paircomp.plri.trt <- summary(emmeans(lmer.plri, pairwise~ treatment|plant|depth)$contrasts)
View(paircomp.plri.trt)
```